### ISSUE TITLE
Run `BiocCheck::BiocCheck()` on the package

### ISSUE THREAD

**Issue by nturaga** [reesyxan/iDA#6]
Hi @reesyxan and Kelly,

Just as a primer for how to handle issues, I thought I'd open one. 

- Run BiocCheck() on your package and fix issues (https://bioconductor.org/packages/release/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#bioccheck) 

Once you resolve this issue, i.e after you've run BiocCheck and fixed the basic ERROR and WARNING messages it outputs, please close it.

**Comment by reesyxan** [comment]
bioccheck has no errors now
